// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4X_WUoUI3QB9nXF2BRiKf0b-UpKOzI04',
    appId: '1:276304148876:web:1f1845057949198d473ea9',
    messagingSenderId: '276304148876',
    projectId: 'chatapp-fbc9d',
    authDomain: 'chatapp-fbc9d.firebaseapp.com',
    storageBucket: 'chatapp-fbc9d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU8PP_HdXh_CQ6Z1aUruFEmKxINLi22yc',
    appId: '1:276304148876:android:fdd3b4e1231efed3473ea9',
    messagingSenderId: '276304148876',
    projectId: 'chatapp-fbc9d',
    storageBucket: 'chatapp-fbc9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuvV7DMKqJ1k0MiycI95PAic9RZWGl1zE',
    appId: '1:276304148876:ios:bafc4e718dd84bb0473ea9',
    messagingSenderId: '276304148876',
    projectId: 'chatapp-fbc9d',
    storageBucket: 'chatapp-fbc9d.appspot.com',
    iosBundleId: 'com.example.firebaseChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuvV7DMKqJ1k0MiycI95PAic9RZWGl1zE',
    appId: '1:276304148876:ios:007e322f3c49a35a473ea9',
    messagingSenderId: '276304148876',
    projectId: 'chatapp-fbc9d',
    storageBucket: 'chatapp-fbc9d.appspot.com',
    iosBundleId: 'com.example.firebaseChat.RunnerTests',
  );
}
